### ISSUE TITLE
[Bug]: 3.16.4 crash on scrolling activity history: `Assertion '!(__hi < __lo)' failed.`

### ISSUE THREAD

**Issue by C0rn3j** [nextcloud/desktop#8265]
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Crashes on scroll.

```
[0] % nextcloud
nextcloud.gui.application: Migrating old config from "/home/user/.local/share/Nextcloud" to "/home/user/.config/Nextcloud"
nextcloud.gui.application: Failed to move the old config directory "/home/user/.local/share/Nextcloud" to new location "/home/user/.config/Nextcloud"
nextcloud.gui.application: Will move the individual files: QList("Nextcloud_sync.log", "Nextcloud_sync.log.1")
nextcloud.gui.account.manager: Checking for accounts versions.
nextcloud.gui.account.manager: Config accounts version: 2
nextcloud.gui.account.manager: Max accounts Version is set to: 13
nextcloud.gui.folder.manager: FolderDefinition::maxSettingsVersion: 13
nextcloud.gui.folder.manager: FolderDefinition::maxSettingsVersion: 13
nextcloud.gui.folder.manager: FolderDefinition::maxSettingsVersion: 13
/usr/include/c++/15.1.1/bits/stl_algo.h:3638: constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = int]: Assertion '!(__hi < __lo)' failed.
[1]    404741 IOT instruction (core dumped)  nextcloud
```

Seems to happen here:

```c++
#39 0x00005ec67880650f in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/nextcloud-client/nextcloud-client/src/gui/main.cpp:208
```

Which is just `return app.exec();`, so not entirely useful I suppose.

### Steps to reproduce

Click on the tray icon, scroll down, crash.

### Expected behavior

No crash.

### Which files are affected by this bug

None.

### Operating system

Linux

### Which version of the operating system you are running.

Arch Linux

### Package

Distro package manager

### Nextcloud Server version

31.0.4

### Nextcloud Desktop Client version

3.16.4

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell

```

### Additional info

```yaml
Operating System: Arch Linux 
KDE Plasma Version: 6.3.5
KDE Frameworks Version: 6.14.0
Qt Version: 6.9.0
Kernel Version: 6.14.6-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 7600X 6-Core Processor
Memory: 61.9 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 4090
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: X670 AORUS ELITE AX
```
